######################## default configuration ####################
baseURL = "https://gray-sand-0ccb3e403.azurestaticapps.net/"
title = "Kulti 22"
theme = "hugo-theme-copper"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com
# default language
defaultContentLanguage = "de"
# disable language
disableLanguages = ["en", "fr"] # desable language from here


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"

#################### default parameters ################################
[params]
logo = "images/logos/Logo_Kulti22_farbig.png"
# Meta data
description = "Jubla: Lieder- und Kulturfest 2022"
author = "Thomas"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
appinsights_instrumentationkey = "85ad0557-4954-4eef-ab02-9f4e0b8cad8b"

eventfrog_link = "https://eventfrog.ch/de/p/festivals/weitere-festivals/lieder-und-kulturfest-2022-6833845387129228352.html"


# Preloader
[params.preloader]
enable = false
preloader = "images/fuenkli/flames_smile_loop_trans.gif" # use jpg, png, svg or gif format.
text1 = "Wilkommen"
text2 = "Kulti 22"
  
############################# social site ########################
[[params.social]]
name = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
name = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"


################################### German language #####################################
[Languages.de]
languageName = "De"
languageCode = "de-ch"
contentDir = "content/german"
weight = 1
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "Developed by Thomas"



############### german navigation ################
# main menu

[[Languages.de.menu.main]]
name = "Home"
URL = ""
weight = 1

[[Languages.de.menu.main]]
name = "Infos"
URL = "infos"
weight = 2

[[Languages.de.menu.main]]
name = "Projekt"
URL = "projekt"
weight = 3

[[Languages.de.menu.main]]
name = "Helfende"
URL = "helfende"
weight = 4

[[Languages.de.menu.main]]
name = "Unterstützen"
URL = "unterstuetzen"
weight = 5

[[Languages.de.menu.main]]
name = "Kontakt"
URL = "kontakt"
weight = 6

# Footer menu
[[Languages.de.menu.footer]]
name = "Häufige Fragen"
URL = "faq"
weight = 1

[[Languages.de.menu.footer]]
name = "Impressum"
URL = "impressum"
weight = 2