---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/de/homepage.yml
  label: Homepage
- type: document
  path: content/german/infos/_index.md
  label: Info
- type: directory
  path: content/german/info-abc
  label: Info ABC
  create: all
  match: "**/*"
- type: document
  path: content/german/ateliers/_index.md
  label: Atelier Seite
- type: directory
  path: content/german/ateliers
  label: Ateliers
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - atelier
- type: document
  path: content/german/gelaendegame/_index.md
  label: Geländegame
- type: document
  path: content/german/spikeball/_index.md
  label: Spikeball
- type: document
  path: content/german/helfende/_index.md
  label: Helfende
- type: document
  path: content/german/acts/_index.md
  label: Acts Seite
- type: directory
  path: content/german/acts
  label: Acts
  create: documents
  match: "**/*"
  exclude: _index.md
- type: directory
  path: content/german/act-contest
  label: Acts Contest
  create: documents
  match: "**/*"
  templates:
  - act
- type: document
  path: content/german/projekt/_index.md
  label: Projekt
- type: document
  path: content/german/unterstuetzen/_index.md
  label: Unterstützen
- type: directory
  path: content/german/sponsors
  label: Sponsors
  create: all
  match: "**/*"
  templates:
  - sponsor
- type: document
  path: content/german/kontakt/_index.md
  label: Kontakt
- type: document
  path: content/german/impressum/_index.md
  label: Impressum
upload_dir: assets/images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
